### ISSUE TITLE
Upgrading to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3 breaks tests

### ISSUE THREAD

**Issue by JohnLCaron** [votingworks/electionguard-kotlin-multiplatform#362]
Upgrading to org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3 from 1.6.4.

gets lots of failures when running complete tests:

kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 10s, the test coroutine is not completing
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:333)
	at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
	at kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:662)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
	at java.base/java.lang.Thread.run(Thread.java:833)

generally doesnt happen when re-unning indivual tests.

Likekely culprit is in TestHelpers: 

fun runTest(f: suspend () -> Unit) {
    // another benefit of having this wrapper code: we don't have to have the OptIn thing
    // at the top of every unit test file
    kotlinx.coroutines.test.runTest { f() }
}

IntelliJ compiler gives error
Cannot access class 'kotlin.coroutines.CoroutineContext'. Check your module classpath for missing or conflicting dependencies
Cannot access class 'kotlin.time.Duration'. Check your module classpath for missing or conflicting dependencies

regress to 1.6.4 thinks work, though same compiler error

**Comment by JohnLCaron** [comment]
Works with deprecated method:

@Deprecated(
    "Define a total timeout for the whole test instead of using dispatchTimeoutMs. " +
        "Warning: the proposed replacement is not identical as it uses 'dispatchTimeoutMs' as the timeout for the whole test!",
    ReplaceWith("runTest(context, timeout = dispatchTimeoutMs.milliseconds, testBody)",
        "kotlin.time.Duration.Companion.milliseconds"),
    DeprecationLevel.WARNING
) // Warning since 1.7.0, was experimental in 1.6.x
public fun runTest(
    context: CoroutineContext = EmptyCoroutineContext,
    dispatchTimeoutMs: Long,
    testBody: suspend TestScope.() -> Unit
): TestResult

seems to mostly work with:

    kotlinx.coroutines.test.runTest(EmptyCoroutineContext, 10_1000.milliseconds, f)

but:

**Comment by JohnLCaron** [comment]
Revert to 1.6.4 for now.

**Comment by JohnLCaron** [comment]
gradle/libs.versions.toml has 
coroutines-version = "1.6.4"
